### PR TITLE
Gradle cleanup

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
Now with the install task you can install the artifact in your local maven repository

**Comment by sgdc3** [comment]
If you merge this i'll be able to host your project on the jenkins of my org. http://ci.xephi.fr/job/bPermissions-Gradle/

**Comment by rymate1234** [comment]
I won't be merging this commit for a couple of reasons:

1. Since this pull request was created I restarted development of the sponge subproject
2. I already host a [jenkins ](http://rymatemc.co.uk/jenkins/job/bPermissions/) and [artifactory](http://rymatemc.co.uk:8081/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/de/bananaco/bPermissions-API/2.12/bPermissions-API-2.12.jar) for auto building / maven repositories

Thanks for the pull request anyway!

**Comment by sgdc3** [comment]
@rymate1234 The maven repository is offline :/

**Pull request closed without merging**
